### ISSUE TITLE
Class Issues

### ISSUE THREAD

**Issue by projetosfsi** [cachewerk/k6#13]
I noticed that in the scripts used we have some classes to identify, for example.

List of Product categories

Login Forms

Etc...

As each WordPress site can be built with different tools, it would be interesting to have documentation teaching which classes should be changed.

But it would be even more interesting if there was a copy of the website you used to do the tests, so we could import it onto our servers for testing purposes.

Could you please tell me which theme you used and plugins you had in your environment to replicate the tests?

**Comment by tillkruss** [comment]
> Could you please tell me which theme you used and plugins you had in your environment to replicate the tests?

https://woocommerce.com/products/storefront/
