### ISSUE TITLE
k6 install over ubuntu server url fails

### ISSUE THREAD

**Issue by osevan** [cachewerk/k6#16]
sudo gpg -k
sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
sudo apt-get update
sudo apt-get install k6

Error: https://dl.k6.io/deb stable InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C780D0BDB1A69C86

Warning: GPG error: https://dl.k6.io/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C780D0BDB1A69C86
Warning: https://dl.k6.io/deb/dists/stable/InRelease: The key(s) in the keyring /usr/share/keyrings/k6-archive-keyring.gpg are ignored as the file has an unsupported filetype.
Error: The repository 'https://dl.k6.io/deb stable InRelease' is not signed.

**Comment by tillkruss** [comment]
Nothing to do with this repository.
