### ISSUE TITLE
Read client header

### ISSUE THREAD

**Issue by tillkruss** [cachewerk/k6#2]
Read cache engine name. May need custom must-use plugin.

**Comment by tillkruss** [comment]
k6 doesn't support tracking metrics like this.

```php
add_action( 'send_headers', function () {
    $client = defined( 'WP_REDIS_CONFIG' )
        ? WP_REDIS_CONFIG['client'] ?? 'phpredis'
        : 'unknown';

    header( "X-Redis-Client: {$client}" );
} );
```

**Comment by tillkruss** [comment]
@kevinohashi Useful for debugging.

**Comment by kevinohashi** [comment]
Nice. Wondering if this could be scaled to many variables like which caching plugins are in use, etc. Could this read more broadly the wp object cache as well?

**Comment by tillkruss** [comment]
Yeah, you could read various names, but each caching plugin is so different, there is no generic way to read who's doing object or page caching. 

I guess you could read if the page was statically cached or not.

**Comment by tillkruss** [comment]
@kevinohashi: I added a page cache rate to all load tests. We'll need to add each individual plugin and their headers or HTML comments to detect a cached response.

**Comment by tillkruss** [comment]
The client is part of the analytics comment now.
